/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AllSongsRouteImport } from './routes/all-songs'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as AlbumAlbumSlugRouteImport } from './routes/album.$albumSlug'
import { Route as ArtistArtistSlugRouteImport } from './routes/artist.$artistSlug'
import { Route as SectionSectionSlugRouteImport } from './routes/section.$sectionSlug'
import { Route as SongSongIdRouteImport } from './routes/song.$songId'
import { Route as SectionSectionSlugFeaturedRouteImport } from './routes/section.$sectionSlug.featured'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AllSongsRoute = AllSongsRouteImport.update({
  id: '/all-songs',
  path: '/all-songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumSlugRoute = AlbumAlbumSlugRouteImport.update({
  id: '/album/$albumSlug',
  path: '/album/$albumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistSlugRoute = ArtistArtistSlugRouteImport.update({
  id: '/artist/$artistSlug',
  path: '/artist/$artistSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionSlugRoute = SectionSectionSlugRouteImport.update({
  id: '/section/$sectionSlug',
  path: '/section/$sectionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdRoute = SongSongIdRouteImport.update({
  id: '/song/$songId',
  path: '/song/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionSlugFeaturedRoute =
  SectionSectionSlugFeaturedRouteImport.update({
    id: '/featured',
    path: '/featured',
    getParentRoute: () => SectionSectionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/all-songs': typeof AllSongsRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugRoute
  '/section/$sectionSlug': typeof SectionSectionSlugRouteWithChildren
  '/song/$songId': typeof SongSongIdRoute
  '/section/$sectionSlug/featured': typeof SectionSectionSlugFeaturedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/all-songs': typeof AllSongsRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugRoute
  '/section/$sectionSlug': typeof SectionSectionSlugRouteWithChildren
  '/song/$songId': typeof SongSongIdRoute
  '/section/$sectionSlug/featured': typeof SectionSectionSlugFeaturedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/all-songs': typeof AllSongsRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugRoute
  '/section/$sectionSlug': typeof SectionSectionSlugRouteWithChildren
  '/song/$songId': typeof SongSongIdRoute
  '/section/$sectionSlug/featured': typeof SectionSectionSlugFeaturedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/all-songs'
    | '/artists'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/library'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trending'
    | '/album/$albumSlug'
    | '/artist/$artistSlug'
    | '/section/$sectionSlug'
    | '/song/$songId'
    | '/section/$sectionSlug/featured'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/all-songs'
    | '/artists'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/library'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trending'
    | '/album/$albumSlug'
    | '/artist/$artistSlug'
    | '/section/$sectionSlug'
    | '/song/$songId'
    | '/section/$sectionSlug/featured'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/all-songs'
    | '/artists'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/library'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trending'
    | '/album/$albumSlug'
    | '/artist/$artistSlug'
    | '/section/$sectionSlug'
    | '/song/$songId'
    | '/section/$sectionSlug/featured'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AlbumsRoute: typeof AlbumsRoute
  AllSongsRoute: typeof AllSongsRoute
  ArtistsRoute: typeof ArtistsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  AlbumAlbumSlugRoute: typeof AlbumAlbumSlugRoute
  ArtistArtistSlugRoute: typeof ArtistArtistSlugRoute
  SectionSectionSlugRoute: typeof SectionSectionSlugRouteWithChildren
  SongSongIdRoute: typeof SongSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-songs': {
      id: '/all-songs'
      path: '/all-songs'
      fullPath: '/all-songs'
      preLoaderRoute: typeof AllSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumSlug': {
      id: '/album/$albumSlug'
      path: '/album/$albumSlug'
      fullPath: '/album/$albumSlug'
      preLoaderRoute: typeof AlbumAlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistSlug': {
      id: '/artist/$artistSlug'
      path: '/artist/$artistSlug'
      fullPath: '/artist/$artistSlug'
      preLoaderRoute: typeof ArtistArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionSlug': {
      id: '/section/$sectionSlug'
      path: '/section/$sectionSlug'
      fullPath: '/section/$sectionSlug'
      preLoaderRoute: typeof SectionSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId': {
      id: '/song/$songId'
      path: '/song/$songId'
      fullPath: '/song/$songId'
      preLoaderRoute: typeof SongSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionSlug/featured': {
      id: '/section/$sectionSlug/featured'
      path: '/featured'
      fullPath: '/section/$sectionSlug/featured'
      preLoaderRoute: typeof SectionSectionSlugFeaturedRouteImport
      parentRoute: typeof SectionSectionSlugRoute
    }
  }
}

interface SectionSectionSlugRouteChildren {
  SectionSectionSlugFeaturedRoute: typeof SectionSectionSlugFeaturedRoute
}

const SectionSectionSlugRouteChildren: SectionSectionSlugRouteChildren = {
  SectionSectionSlugFeaturedRoute: SectionSectionSlugFeaturedRoute,
}

const SectionSectionSlugRouteWithChildren =
  SectionSectionSlugRoute._addFileChildren(SectionSectionSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AlbumsRoute: AlbumsRoute,
  AllSongsRoute: AllSongsRoute,
  ArtistsRoute: ArtistsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  AlbumAlbumSlugRoute: AlbumAlbumSlugRoute,
  ArtistArtistSlugRoute: ArtistArtistSlugRoute,
  SectionSectionSlugRoute: SectionSectionSlugRouteWithChildren,
  SongSongIdRoute: SongSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
